export const INTEGRAL = 'Integral'
export const SUMMATION = 'Summation'
export const BIG_OPERATOR = 'Big Operator'
export const LIMIT = 'Limit'
export const FRACTION = 'Fraction'
export const MATRIX = 'Matrix'
export const LOG = 'Log'
export const ACCENT = 'Accent'
